# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workspace\Byakugan\Byakugan\src\main\python\Byakugan\gui\windows\ui\ui_about.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(432, 196)
        self.aboutDlgLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.aboutDlgLayout.setObjectName("aboutDlgLayout")
        self.titleHBoxLayout = QtWidgets.QHBoxLayout()
        self.titleHBoxLayout.setObjectName("titleHBoxLayout")
        self.aboutDlgLayout.addLayout(self.titleHBoxLayout)
        self.tw_tabs = QtWidgets.QTabWidget(AboutDialog)
        self.tw_tabs.setObjectName("tw_tabs")
        self.aboutTab = QtWidgets.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.aboutTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.aboutTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.aboutTab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tw_tabs.addTab(self.aboutTab, "")
        self.authorTab = QtWidgets.QWidget()
        self.authorTab.setObjectName("authorTab")
        self.authorTabLayout = QtWidgets.QVBoxLayout(self.authorTab)
        self.authorTabLayout.setObjectName("authorTabLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.authorTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setText("Abdalla Mohamed")
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setText("<a href=\"mailto:sharpcodex@gmail.com\">sharpcodex@gmail.com</a>")
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.authorTabLayout.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.authorTabLayout.addItem(spacerItem2)
        self.tw_tabs.addTab(self.authorTab, "")
        self.thanksTab = QtWidgets.QWidget()
        self.thanksTab.setObjectName("thanksTab")
        self.thanksTabLayout = QtWidgets.QVBoxLayout(self.thanksTab)
        self.thanksTabLayout.setContentsMargins(0, 0, 0, 0)
        self.thanksTabLayout.setObjectName("thanksTabLayout")
        self.textBrowserThanks = QtWidgets.QTextBrowser(self.thanksTab)
        self.textBrowserThanks.setOpenExternalLinks(True)
        self.textBrowserThanks.setObjectName("textBrowserThanks")
        self.thanksTabLayout.addWidget(self.textBrowserThanks)
        self.tw_tabs.addTab(self.thanksTab, "")
        self.translationTab = QtWidgets.QWidget()
        self.translationTab.setObjectName("translationTab")
        self.translationTabLayout = QtWidgets.QVBoxLayout(self.translationTab)
        self.translationTabLayout.setContentsMargins(0, 0, 0, 0)
        self.translationTabLayout.setObjectName("translationTabLayout")
        self.textBrowserTranslation = QtWidgets.QTextBrowser(self.translationTab)
        self.textBrowserTranslation.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowserTranslation.setObjectName("textBrowserTranslation")
        self.translationTabLayout.addWidget(self.textBrowserTranslation)
        self.tw_tabs.addTab(self.translationTab, "")
        self.librariesTab = QtWidgets.QWidget()
        self.librariesTab.setObjectName("librariesTab")
        self.librariesTabLayout = QtWidgets.QVBoxLayout(self.librariesTab)
        self.librariesTabLayout.setObjectName("librariesTabLayout")
        self.label = QtWidgets.QLabel(self.librariesTab)
        self.label.setObjectName("label")
        self.librariesTabLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.librariesTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.librariesTabLayout.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelZlibVer = QtWidgets.QLabel(self.librariesTab)
        self.labelZlibVer.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelZlibVer.setObjectName("labelZlibVer")
        self.gridLayout.addWidget(self.labelZlibVer, 4, 1, 1, 1)
        self.labelBoostVer = QtWidgets.QLabel(self.librariesTab)
        self.labelBoostVer.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelBoostVer.setObjectName("labelBoostVer")
        self.gridLayout.addWidget(self.labelBoostVer, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.librariesTab)
        self.label_10.setText("qtawesome")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.librariesTab)
        self.label_8.setText("Qt")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.librariesTab)
        self.label_9.setText("OpenCV")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.labelQtVer = QtWidgets.QLabel(self.librariesTab)
        self.labelQtVer.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelQtVer.setObjectName("labelQtVer")
        self.gridLayout.addWidget(self.labelQtVer, 0, 1, 1, 1)
        self.labelLibtVer = QtWidgets.QLabel(self.librariesTab)
        self.labelLibtVer.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLibtVer.setObjectName("labelLibtVer")
        self.gridLayout.addWidget(self.labelLibtVer, 1, 1, 1, 1)
        self.labelOpensslVer = QtWidgets.QLabel(self.librariesTab)
        self.labelOpensslVer.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelOpensslVer.setObjectName("labelOpensslVer")
        self.gridLayout.addWidget(self.labelOpensslVer, 3, 1, 1, 1)
        self.librariesTabLayout.addLayout(self.gridLayout)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.librariesTabLayout.addItem(spacerItem4)
        self.tw_tabs.addTab(self.librariesTab, "")
        self.aboutDlgLayout.addWidget(self.tw_tabs)

        self.retranslateUi(AboutDialog)
        self.tw_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About Byakugan"))
        self.label_3.setText(_translate("AboutDialog", "Byakugan "))
        self.label_4.setText(_translate("AboutDialog", "Byakugan is a smart image viewer, editor, and organizer which uses the latest computer vision technologies to make managing digital photos a \'snap\'"))
        self.tw_tabs.setTabText(self.tw_tabs.indexOf(self.aboutTab), _translate("AboutDialog", "About"))
        self.groupBox_2.setTitle(_translate("AboutDialog", "Current maintainer"))
        self.label_14.setText(_translate("AboutDialog", "Name:"))
        self.label_16.setText(_translate("AboutDialog", "E-mail:"))
        self.tw_tabs.setTabText(self.tw_tabs.indexOf(self.authorTab), _translate("AboutDialog", "Author"))
        self.tw_tabs.setTabText(self.tw_tabs.indexOf(self.thanksTab), _translate("AboutDialog", "Special Thanks"))
        self.tw_tabs.setTabText(self.tw_tabs.indexOf(self.translationTab), _translate("AboutDialog", "Translators"))
        self.label.setText(_translate("AboutDialog", "Byakugan was built with the following libraries:"))
        self.labelBoostVer.setText(_translate("AboutDialog", "https://github.com/spyder-ide/qtawesome"))
        self.labelQtVer.setText(_translate("AboutDialog", "https://www.qt.io/"))
        self.labelLibtVer.setText(_translate("AboutDialog", "https://opencv.org/"))
        self.tw_tabs.setTabText(self.tw_tabs.indexOf(self.librariesTab), _translate("AboutDialog", "Libraries"))

