# App
ORGANIZATION_NAME = 'Thaka'
ORGANIZATION_DOMAIN = 'Thaka.sd'
APPLICATION_NAME = 'Byakugan'
DEFAULT_APP_THEME = 'modern-dark'
DEFAULT_APP_COLOR = 'green'

# UI
WINDOW_HEIGHT_P = 0.8
MAX_WINDOW_HEIGHT_P = 0.9
WINDOW_WIDTH_P = 0.5
MAX_WINDOW_WIDTH_P = 0.95
