# App
ORGANIZATION_NAME = 'Thaka'
ORGANIZATION_DOMAIN = 'Thaka.sd'
APPLICATION_NAME = 'Byakugan'
DEFAULT_APP_THEME = 'modern-dark'
DEFAULT_APP_COLOR = 'green'

# Viewer Window
VUI_WINDOW_HEIGHT_P = 0.8
VUI_WINDOW_WIDTH_P = 0.5
VUI_SAVE_WINDOW_GEOMETRY = False
VUI_SHOW_STATUS_BAR = False
